### PR TITLE
174 fe create add edit view company modal

### PR DESCRIPTION
**Pull request by JustineLapura**
- created company add modal 
image
- created company edit modal 
image
- created company view modal and replaced the old template temporarily 
image
- Updated client card design 
image

### CODE REVIEW

**Comment by jerommiole** [comment]
Please update the Modal view
image

**Comment by jerommiole** [comment]
Update the file name like in the image below:
image

**Comment by JustineLapura** [comment]
image
image

**Comment by JustineLapura** [comment]
update Done sir!

**Pull request merged**
